---
- name: Usage block and rescue
  hosts: serverc.lab.example.com 
  become: true
  tasks:
  - block:
    - name: Install the package
      ansible.builtin.dnf:
        name: telnet
        state: latest
    rescue:
      - name: Custom message
        ansible.builtin.debug:
          msg: "Rescue works"
    always:
      - name: Print custom message - always
        ansible.builtin.debug:
          msg: "I will always run"
