---
- name: Create users with different groups 
  hosts: serverc.lab.example.com 
  become: true
  tasks:
    - name: Create the group
      ansible.builtin.group:
        name: apache
        state: present

    - name: Create user from a list
      loop:
        - { name: 'testuser1', groups: 'wheel' }
        - { name: 'testuser2', groups: 'apache' }
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        state: present
