---
- name: Deploy the security policies
  hosts: "{{ my_host | default('serverb.lab.example.com') }}"
  become: true
  tasks:
    - name: Install the required packages
      ansible.builtin.dnf:
        name: firewalld
        state: latest

    - name: Configure the ports for access
      ansible.builtin.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled

    - name: Start and enable the service
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
...

