---
- name: Demo on using variables
  hosts: serverb.lab.example.com
  gather_facts: no
  tasks:
    - name: Display the variable usage
      ansible.builtin.debug:
        msg: "The custom variable has the value {{ my_var }}"
...
