---
- name: Using vars_files 
  hosts: dbserver
  become: true
  vars_files:
    - userinfo.yml
  tasks:
    - name: Create the account using the variable defined in a separate file
      ansible.builtin.user:
        name: "{{ my_user }}"
        uid: 2001
        shell: /bin/bash
        update_password: on_create
        password: '$6$GUeOAcF0BLw7Z6bm$wRustFbzcFuVUVIXlZ.KUU7nTW/IdQI0SiIvem4dEfrqLlVvG16tCijMAitteh7DzNLeFpi1i2xjFalsJZkgv.'
...
