---
- name: Create a partition
  hosts: serverb.lab.example.com
  become: true
  roles:
  - name: redhat.rhel_system_roles.storage
    storage_volumes:
      - name: extradisk
        type: disk
        disks:
          - /dev/vdb
        fs_type: xfs
        mount_point: /opt/extra
